echo "AWS_S3_LAMBDA_CODE_STORAGE= $AWS_S3_LAMBDA_CODE_STORAGE"
echo "AWS_S3_GENERATED_DOCUMENTS_BUCKET= $AWS_S3_GENERATED_DOCUMENTS_BUCKET"
echo "AWS_S3_DOCUMENT_TEMPLATES_BUCKET= $AWS_S3_DOCUMENT_TEMPLATES_BUCKET"
echo "AWS_REGION= $AWS_REGION"
echo "AWS_STACK_NAME= $AWS_STACK_NAME"

sam deploy \
    --region $AWS_REGION \
    --stack-name $AWS_STACK_NAME \
    --template-file build/packaged.yml \
    --capabilities CAPABILITY_IAM